version: "3.8"
services:
  app:
    container_name: "gobel-client-example"
    env_file: "./app/.env"
    build:
        context: "./app"
        dockerfile: "Dockerfile"
    command: realize start --run
    ports:
      - "8081:8081"
    volumes:
      - ./app:/go/src/github.com/bmf-san/gobel-client-example/app
    networks:
      - gobel_link
  nginx:
    container_name: "gobel-client-example-nginx"
    build:
        context: "./nginx"
        dockerfile: "Dockerfile"
    ports:
      - "81:80"
    networks:
      - gobel_link
    depends_on:
      - app
networks:
    gobel_link:
        external: true