version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  lint:
    parameters:
      version:
        type: string
      modules:
        type: boolean
        default: true
    docker:
      - image: "cimg/go:<< parameters.version >>"
    working_directory: ~/go/src/github.com/bmf-san/gobel-client-example
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "Go version"
          command: go version
      - run:
          name: "Install tools"
          command: |
            if [[ << parameters.version >> = 1.18 ]]; then
              make install-staticcheck
            fi
      - run:
          name: "Run gofmt"
          command: make gofmt
      - run:
          name: "Run vet"
          command: make vet
      - run:
          name: "Run staticcheck"
          command: >
            if [[ << parameters.version >> = 1.18 ]]; then
              make staticcheck
            fi
  test:
    parameters:
      version:
        type: string
      modules:
        type: boolean
        default: true
    docker:
      - image: "cimg/go:<< parameters.version >>"
    working_directory: ~/go/src/github.com/bmf-san/gobel-client-example
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "Go version"
          command: go version
      - run:
          name: "Fetch dependencies"
          command: make mod
      - run:
          name: "Install tools"
          command: >
            if [[ << parameters.version >> = 1.18 ]]; then
              make install-staticcheck
            fi
      - run:
          name: "Run test"
          command: make test
      - run:
          name: Build go
          command: make build
      - run:
          name: Create a temporary directory for artifacts
          command: mkdir -p /tmp/artifacts
      - run:
          name: Generate coverage
          command: make test-cover OUT=<< parameters.version >>.out
      - codecov/upload:
          file: ./app/<< parameters.version >>.out

workflows:
  tests:
    jobs:
      - lint:
          matrix:
            parameters:
              version: ["1.20", "1.19"]
      - test:
          matrix:
            parameters:
              version: ["1.20", "1.19"]