FROM golang:1.20.0-alpine

WORKDIR /go/gobel-client-example/app

RUN apk update && \
    apk upgrade && \
    apk add --no-cache libc-dev gcc git openssh openssl bash && \
    go install github.com/cosmtrek/air@latest && \
    go install golang.org/x/lint/golint@latest

CMD air -c .air.toml
