FROM golang:1.13.0-alpine as builder

RUN apk update && \
    apk upgrade && \
    apk add --no-cache libc-dev gcc git openssh openssl bash && \
    go get -u golang.org/x/lint/golint

WORKDIR /go/src/gobel-client-example

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

RUN go build -o app

FROM alpine

COPY --from=builder /go/src/gobel-client-example/app ./
COPY --from=builder /go/src/gobel-client-example/view/ /view/

CMD ["./app"]