FROM nginx:1.21.3-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./conf.d/gobel-client-example.conf /etc/nginx/conf.d/gobel-client-example.conf

RUN ln -sf /dev/stdout /var/log/nginx/access_gobel_client_example.log \
    && ln -sf /dev/stderr /var/log/nginx/error_gobel_client_example.log \